### ISSUE TITLE
S3 Source Connector

### ISSUE THREAD

**Issue by mcandre** [qubole/streamx#12]
Could streamx also provide an S3 Source connector, for reading data from S3 back onto Kafka? This would help in a backup/restore use case.

**Comment by PraveenSeluka** [comment]
Hi @mcandre This is interesting, can you may be talk more about the use-case. Is it because, data is lost in Kafka for some reason and you need to restore back from s3, so that other consumers can read ? 

This is not something in the roadmap of streamx, as its primarily sink connector - but it can expand to solve these use-cases(nice to have)

**Comment by PraveenSeluka** [comment]
@mcandre am closing this issue for now. This is not in the scope of StreamX short term. I will open it, if we plan to do this.
